#[cfg(test)]
mod tests {
    use unipotato::{Request, Response, launch, routes, __register_route, handler};
    
    // ============ Test Helpers ============
    
    // Mock handler functions for testing
    #[allow(dead_code)]
    async fn mock_handler(_req: Request) -> Response {
        handler::html("OK")
    }
    
    #[allow(dead_code)]
    async fn mock_handler_2(_req: Request) -> Response {
        handler::html("OK")
    }
    
    // Mock module structure for testing module::handler syntax
    mod test_handlers {
        use unipotato::{Request, Response, handler};
        
        pub async fn index(_req: Request) -> Response {
            handler::html("OK")
        }
        
        pub async fn about(_req: Request) -> Response {
            handler::html("About")
        }
        
        // These would normally be generated by #[get] macro
        #[allow(non_camel_case_types)]
        pub struct __ROUTE_INFO_INDEX;
        impl __ROUTE_INFO_INDEX {
            pub fn register() {
                // Mock registration
            }
        }
        
        #[allow(non_camel_case_types)]
        pub struct __ROUTE_INFO_ABOUT;
        impl __ROUTE_INFO_ABOUT {
            pub fn register() {
                // Mock registration
            }
        }
    }
    
    // ============ Tests for `launch!` Macro ============
    
    #[test]
    fn test_launch_with_port() {
        // Test launch! with explicit port
        let server = launch!(3000);
        assert_eq!(server.port(), 3000);
    }
    
    #[test]
    fn test_launch_default_port() {
        // Test launch! without port (should default to 8000)
        let server = launch!();
        assert_eq!(server.port(), 8000);
    }
    
    #[test]
    fn test_launch_with_expression() {
        // Test launch! with expression as port
        let port = 5000 + 500;
        let server = launch!(port);
        assert_eq!(server.port(), 5500);
    }
    
    #[test]
    fn test_launch_with_const() {
        // Test launch! with const
        const PORT: u16 = 9000;
        let server = launch!(PORT);
        assert_eq!(server.port(), 9000);
    }
    
    // ============ Tests for `__register_route!` Macro ============
    
    #[test]
    fn test_register_route_expands() {
        // Test that __register_route! expands correctly
        // This tests the paste functionality
        __register_route!(test_handlers, index);
        __register_route!(test_handlers, about);
        // If this compiles, the macro expansion is correct
    }
    
    #[test]
    fn test_register_route_uppercase_conversion() {
        // Test that handler name is converted to uppercase
        // The macro should convert `index` to `INDEX`
        mod nested {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_TESTHANDLER;
            impl __ROUTE_INFO_TESTHANDLER {
                pub fn register() {}
            }
            
            #[allow(dead_code)]
            pub async fn testhandler(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("OK")
            }
        }
        
        __register_route!(nested, testhandler);
        // If this compiles, uppercase conversion works
    }
    
    // ============ Tests for `routes!` Macro - Variant 1 ============
    
    #[test]
    fn test_routes_macro_compiles() {
        // Test that routes! macro with module::handler syntax compiles
        // and returns a closure
        let register = routes! {
            test_handlers::index,
            test_handlers::about,
        };
        
        // Should be a closure
        register();
    }
    
    #[test]
    fn test_routes_single_handler() {
        // Test routes! with single handler
        let register = routes! {
            test_handlers::index
        };
        register();
    }
    
    #[test]
    fn test_routes_with_trailing_comma() {
        // Test that trailing comma is allowed
        let register = routes! {
            test_handlers::index,
            test_handlers::about,
        };
        register();
    }
    
    #[test]
    fn test_routes_without_trailing_comma() {
        // Test without trailing comma
        let register = routes! {
            test_handlers::index,
            test_handlers::about
        };
        register();
    }
    
    #[test]
    fn test_routes_type_checking() {
        // Test that the macro validates function signature
        // This should compile because test_handlers::index has correct signature
        let register = routes! {
            test_handlers::index
        };
        
        // The macro includes: let _ = test_handlers::index as fn(Request) -> _;
        // This validates the function signature at compile time
        register();
    }
    
    #[test]
    fn test_routes_multiple_modules() {
        // Test routes! with handlers from different logical modules
        mod module_a {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_HANDLER_A;
            impl __ROUTE_INFO_HANDLER_A {
                pub fn register() {}
            }
            pub async fn handler_a(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("A")
            }
        }
        
        mod module_b {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_HANDLER_B;
            impl __ROUTE_INFO_HANDLER_B {
                pub fn register() {}
            }
            pub async fn handler_b(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("B")
            }
        }
        
        let register = routes! {
            module_a::handler_a,
            module_b::handler_b
        };
        register();
    }
    
    // ============ Integration Tests ============
    
    #[test]
    fn test_launch_and_routes_integration() {
        // Test that launch! and routes! work together
        let _server = launch!(8080);
        
        let register = routes! {
            test_handlers::index,
            test_handlers::about
        };
        
        register();
        // If this compiles and runs, integration works
    }
    
    #[test]
    fn test_macro_hygiene() {
        // Test that macros don't pollute namespace
        {
            let _server = launch!(3000);
        }
        {
            let _server = launch!(4000);
        }
        // If this compiles, macros maintain proper hygiene
    }
    
    // ============ Edge Case Tests ============
    
    #[test]
    fn test_routes_empty() {
        // Test routes! with no handlers - creates an empty closure
        let _register = routes! {};
        // Empty closure returns (), which is fine
    }
    
    #[test]
    fn test_nested_module_path() {
        // Note: The routes! macro only supports single-level module paths (module::handler)
        // For nested modules, flatten the structure or use a different approach
        mod level2 {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_DEEP;
            impl __ROUTE_INFO_DEEP {
                pub fn register() {}
            }
            pub async fn deep(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("Deep")
            }
        }
        
        let register = routes! {
            level2::deep
        };
        register();
    }
    
    #[test]
    fn test_handler_name_with_underscores() {
        // Test handler names with underscores
        mod handlers {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_GET_ALL_USERS;
            impl __ROUTE_INFO_GET_ALL_USERS {
                pub fn register() {}
            }
            pub async fn get_all_users(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("Users")
            }
        }
        
        let register = routes! {
            handlers::get_all_users
        };
        register();
    }
    
    #[test]
    fn test_handler_name_with_numbers() {
        // Test handler names with numbers
        mod handlers {
            #[allow(non_camel_case_types)]
            pub struct __ROUTE_INFO_HANDLER_V2;
            impl __ROUTE_INFO_HANDLER_V2 {
                pub fn register() {}
            }
            pub async fn handler_v2(_req: unipotato::Request) -> unipotato::Response {
                unipotato::handler::html("V2")
            }
        }
        
        let register = routes! {
            handlers::handler_v2
        };
        register();
    }
    
    // ============ Documentation Tests ============
    
    /// Test that demonstrates basic launch! usage
    #[test]
    fn test_launch_example() {
        // Example: launch server on custom port
        let server = launch!(3000);
        assert_eq!(server.port(), 3000);
        
        // Example: launch server on default port
        let server_default = launch!();
        assert_eq!(server_default.port(), 8000);
    }
    
    /// Test that demonstrates basic routes! usage
    #[test]
    fn test_routes_example() {
        // Example: register multiple route handlers
        let register = routes! {
            test_handlers::index,
            test_handlers::about,
        };
        
        // Call the closure to register routes
        register();
    }
}